packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

catalog:
  "@types/node": ^22.13.10
  eslint: ^9.22.0
  prettier: ^3.5.3
  typescript: ^5.8.2
  typescript-eslint: ^8.26.1

catalogs:
  react-19:
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
    react-dom: ^19.0.0
    react: ^19.0.0
