packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

catalog:
  "@ianvs/prettier-plugin-sort-imports": ^4.4.1
  "@tailwindcss/postcss": ^4.0.14
  "@types/node": ^22.13.10
  eslint: ^9.22.0
  postcss: ^8.5.3
  prettier: ^3.5.3
  tailwindcss: ^4.0.14
  typescript-eslint: ^8.26.1
  typescript: ^5.8.2

catalogs:
  next-15:
    next: ^15.2.1
  react-19:
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
    react-dom: ^19.0.0
    react: ^19.0.0
